from hyperbrowser.models.consts import POLLING_ATTEMPTS

DEFAULT_POLLING_RETRY_ATTEMPTS = POLLING_ATTEMPTS
DEFAULT_POLLING_RETRY_DELAY_SECONDS = 0.5
DEFAULT_POLL_INTERVAL_SECONDS = 2.0
DEFAULT_MAX_WAIT_SECONDS = 600.0
